server {
    listen 80;

    # Portal
    location / {
        proxy_pass http://portal:8501;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # calendar
    location /tools/calendar/ {
        proxy_pass http://calendar:8501/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # email-reader
    location /tools/email-reader/ {
        proxy_pass http://email-reader:8501/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # job-tracker
    location /tools/job-tracker/ {
        proxy_pass http://job-tracker:8501/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # mock-tool
    location /tools/mock-tool/ {
        proxy_pass http://mock-tool:8501/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # todolist
    location /tools/todolist/ {
        proxy_pass http://todolist:8501/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
